### ISSUE TITLE
[IX] Add documentation for metadata extraction - EN

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazi-documentation#29]
The new new feature of metadata extraction must be properly documented in the Administrator’s guide.
```[tasklist]
### Tasks
- [x] Create article structure
- [x] Gather detailed information about the feature from Jaume
- [x] Create a first draft of the content
- [x] Get reviews from tech and programmes team
- [x] Update content
- [x] Publish
```
