### ISSUE TITLE
[EN] Add documentation for paragraph extraction

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazi-documentation#50]
The new feature of paragraph extraction must be properly documented in the Administrator’s guide.

### Tasks
- [x] Create article structure
- [x] Create a first draft of the content: [Preview](https://uwazi--55.org.readthedocs.build/en/55/admin-docs/paragraph-extraction.html)
- [x] Get reviews from tech and programmes team
- [ ] Update contect
- [x] Publish

**Comment by aphilop** [comment]
First task completed through: https://github.com/huridocs/uwazi-documentation/pull/51
